### ISSUE TITLE
Pre-commit hooks for flake8 (like autopep8)

### ISSUE THREAD

**Issue by jackmoody11** [addisonlynch/iexfinance#105]
I was wondering if it would be beneficial to add a [pre-commit hook](https://github.com/pre-commit/pre-commit) to run something like [autopep8](https://github.com/hhatto/autopep8) to avoid having to fix all errors manually after doing a flake8 check?

**Comment by addisonlynch** [comment]
I think this project is a bit small for hooks as it is currently, but I think it may be a good idea down the road. I will leave this issue open for further discussion.

**Comment by addisonlynch** [comment]
Going to go ahead and close this. Linting should be done before committing. May add further checks to CI.
