### ISSUE TITLE
Setting environment to use IEXCloud API

### ISSUE THREAD

**Issue by MichaelPHartmann** [addisonlynch/iexfinance#112]
## Summary (include Python version)
I cannot figure out how to utilize the new IEX Cloud API.
I am using Python 3.6.1 on Mac OS X (Version 10.13.6).
I am new to using Python so I am sure I am just missing something.

### Date/time of issue
February 2019

### Expected behavior
Use the iexfinance package to retrieve get_balance_sheet, get_income_statement, and get_cash_flow.
Expected return is a pandas dataframe with indexed values.

### Actual behavior
I set IEX_API_VERSION=iexcloud-beta in my bash shell and it shows up when I enter 'env'.
When I run the program instead of printing the data I get this message:
'StockReader' object has no attribute 'get_balance_sheet'
I do not know what I am missing because like I said I am very new to python.

Thank you.

**Comment by addisonlynch** [comment]
Can you post a code snippet that is causing the issue? Thanks!

**Comment by CycleMichael94** [comment]
From my bash shell:
TERM_PROGRAM=Apple_Terminal
SHELL=/bin/bash
IEX_API_VERSION=iexcloud-beta

Just writing a little snippet to test out the functionality and to look through the data:
`import pandas
import iexfinance
from iexfinance.stocks import Stock


aapl = Stock('AAPL', output_format='pandas')
print(aapl.get_balance_sheet())`

**Comment by addisonlynch** [comment]
This should work upon upgrading to 0.4.0. Try ``pip install --upgrade iexfinance``

**Comment by ishupradhan** [comment]
@addisonlynch 
I am able to run this:
```
from iexfinance.stocks import Stock
Stock("AAPL").get_quote()
```

but

**Comment by noobmaster29** [comment]
I have the same issue. 

IEXQueryError: An error occurred while making the query.
