### ISSUE TITLE
IEX Cloud Updates

### ISSUE THREAD

**Issue by addisonlynch** [addisonlynch/iexfinance#115]
## Summary

This issue tracks the updates to IEX Cloud beta and provides a roadmap for their implementation in ``iexfinance``.

### Account

* [ ] Message Cutoff Endpoint (https://iexcloud.io/docs/api/#message-cutoff)

### Stocks

* [ ] Advanced Stats (https://iexcloud.io/docs/api/#advanced-stats)
* [ ] As Reported Financials (https://iexcloud.io/docs/api/#as-reported-financials) - _time series endpoint_
* [ ] Intraday Prices Endpoint (https://iexcloud.io/docs/api/#intraday-prices)
* [ ] ``max`` parameter to chart endpoint
* [ ] Recommendation Trends endpoint (https://iexcloud.io/docs/api/#recommendation-trends)

### Reference Data

* [ ] International Symbols (https://iexcloud.io/docs/api/#international-symbols
* [ ] International Exchanges (https://iexcloud.io/docs/api/#international-symbols
* [ ] U.S. Exchanges (https://iexcloud.io/docs/api/#u-s-exchanges)
* [ ] U.S Holidays and Trading Dates (https://iexcloud.io/docs/api/#u-s-holidays-and-trading-dates)
* [ ] Sectors (https://iexcloud.io/docs/api/#sectors)
* [ ] Tags (https://iexcloud.io/docs/api/#tags)
* [ ] ISIN Mapping (https://iexcloud.io/docs/api/#isin-mapping)
* [ ] Mutual Fund Symbols (https://iexcloud.io/docs/api/#mutual-fund-symbols)
* [ ] OTC Symbols (https://iexcloud.io/docs/api/#otc-symbols)
* [ ] FX Symbols (https://iexcloud.io/docs/api/#fx-symbols)
* [ ] Options Symbols (https://iexcloud.io/docs/api/#options-symbols)

### Forex / Currencies

* [ ] Exchange Rates (https://iexcloud.io/docs/api/#exchange-rates)

### Stocks

* [x] Institutional Ownership endpoint (https://iexcloud.io/docs/api/#institutional-ownership)
* [x] Fund Ownership Endpoint (https://iexcloud.io/docs/api/#fund-ownership)
* [x] Insider Roster endpoint (https://iexcloud.io/docs/api/#insider-roster)
* [x] Insider Summary (https://iexcloud.io/docs/api/#insider-summary)
* [x] Insider Transactions (https://iexcloud.io/docs/api/#insider-transactions)
* [x] ``chartByDay`` parameter for Historical Prices

### API Data

* [x] CEO Compensation Alternative Data (https://iexcloud.io/docs/api/#ceo-compensation)
* [x] Data Points (https://iexcloud.io/docs/api/#data-points)
* [x] Time Series (https://iexcloud.io/docs/api/#time-series)

### Options

* [x] End of Day Options (https://iexcloud.io/docs/api/#end-of-day-options)

### Misc
* [x] Sandbox environment (see #116 for more details)

**Comment by lbottan** [comment]
Any idea of when the international symbols/exchange support is going to be implemented?
