### ISSUE TITLE
Add support for IEX Cloud sandbox environment

### ISSUE THREAD

**Issue by addisonlynch** [addisonlynch/iexfinance#116]
## Summary

Per IEX Cloud [docs](https://iexcloud.io/docs/api/#sandbox)

> Every account will be assigned two test tokens available via the Console. All the same endpoints as production will be available in the Sandbox Environment. Please note API data will be manipulated to scramble values, and is not suitable for production usage. We’ve also updated the Usage Report to allow you to view the number of test messages the same way as production message usage.

> How to use
The base url is https://sandbox.iexapis.com
Your test token is available on the console by click the “View Test Data” toggle in the nav.
All tier features are enforced at this time, but you are not limited by the number of calls you can make. Your are not charged for test usage.
Test tokens look like Tpk_ and Tsk_.
To make a call for test data, use the same url, but pass your test token.

**Comment by addisonlynch** [comment]
There are a number of provider-related issues that have been raised in regards to migrating the ``iexfinance`` test suite to the IEX Cloud sandbox environment:

* Randomization of text fields (``primaryExchange`` in crypto) - see https://github.com/iexg/IEX-API/issues/868
* Certain endpoints not available with sandbox environment
  * Account - see https://github.com/iexg/IEX-API/issues/867

**Comment by Danabs82** [comment]
Has this been resolved?  Not being able to use the sandbox basically kills the usefulness of this library.
