### ISSUE TITLE
Server side error: 400

### ISSUE THREAD

**Issue by AwesomeCap** [addisonlynch/iexfinance#118]
## Summary (include Python version)
Can't get it to work. After changing to beta-version and putting in the API Key.. but now, when running the Read-me code for beginners (getting the Apple, Tesla stock and getting the symbols) I'm getting a server-side error:400.

Version: Python3.6

### Date/time of issue
2019-03-18

### Expected behavior
Hoped for getting the get_symbols to work, instead it gave a 400 status code instead.

### Actual behavior
```
Traceback (most recent call last):
    get_symbols()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/iexfinance/refdata/__init__.py", line 13, in get_symbols
    return Symbols(**kwargs).fetch()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/iexfinance/base.py", line 192, in fetch
    data = self._execute_iex_query(url)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/iexfinance/base.py", line 148, in _execute_iex_query
    return self._handle_error(response)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/iexfinance/base.py", line 161, in _handle_error
    raise auth_error("The query could not be completed. "
iexfinance.utils.exceptions.IEXAuthenticationError: The query could not be completed. There was a client-side error with your request.
```

**Comment by addisonlynch** [comment]
How are you storing your API key, and which are you using? This is a *client-side* error that is often raised when an incorrect authentication token is passed.

**Comment by AwesomeCap** [comment]
I did a lazy thing and stored the key inside the script. It's possible that using env instead will solve it. Haven't got my grip on env yet.

**Comment by jacobesplin** [comment]
I am, also, having this issue. This is how I am coding it, which has worked in the past before a token was  added,
get_historical_data("aapl", "2019-01-01", "2019-05-26", output_format='pandas',token="<token>")
but now I am receiving this error.
iexfinance.utils.exceptions.IEXAuthenticationError: The query could not be completed. There was a client-side error with your request.

**Comment by jacobesplin** [comment]
Uninstalling old version of iexfinance and reinstalling worked
