### ISSUE TITLE
Multiple financial statements with last>=1 parameter fails for pandas

### ISSUE THREAD

**Issue by amittleider** [addisonlynch/iexfinance#119]
```
from iexfinance.stocks import Stock
aapl = Stock("AAPL", output_format='pandas')
balance_sheet = aapl.get_balance_sheet(last=4)
```

This returns a data frame with 1 row, where it should return a dataframe with 4 rows. 

~~The above is the main problem, but I have a second question: it seems that from time to time~~, ~~pandas dataframes are organized with the company as the column, and sometimes with the~~ ~~company as the row. I'm wondering what the logic is behind it? To me, it seems that financial~~ ~~statements should be a dataframe with a MultiIndex of company name and report date.~~ (moved to #121) 

Nice work on the repo!

**Comment by addisonlynch** [comment]
Thanks, @amittleider, looking into this

**Comment by addisonlynch** [comment]
This is an issue with the following as well:

* ``get_income_statement``
* ``get_cash_flow``

and could be implemented in

* ``get_earnings``
* ``get_financials``

**Comment by zhenyulin** [comment]
this parameter should be in the document as well, currently, only `period` is documented
