### ISSUE TITLE
Many stocks fields methods return errors

### ISSUE THREAD

**Issue by addisonlynch** [addisonlynch/iexfinance#127]
## Summary (include Python version)

A number of stocks field method endpoints have changed, and as such are no longer working.

This includes field methods such as (incomplete list):

* ``get_sector``
* ``get_primary_exchange``

**Comment by jackmoody11** [comment]
I believe the "sector" field changed from "quote" to "company" and the "primary_exchange" field changed from "quote" to "company" with the new field name being "exchange". I believe the only changes that need to be made are in stocks/base.py.

The example from the [company endpoint](https://iexcloud.io/docs/api/#company) makes it seem like only the primary exchange is listed, however, the current description is blank. I am not sure if 

```GET /stock/{symbol}/company```

would return an exchange field with a list of exchanges if the stock were traded on multiple exchanges. May need to wait for the docs to be updated.

**Comment by jackmoody11** [comment]
@addisonlynch I believe this issue is closed now.
