### ISSUE TITLE
How to request OTC data

### ISSUE THREAD

**Issue by Seroplex** [addisonlynch/iexfinance#128]
## Summary (include Python version)

IEX provide OTC market daily data. However I could not find how to get it

using the wrapper.

**Comment by addisonlynch** [comment]
This is *in-progress*

**Comment by addisonlynch** [comment]
Apologies for the delay in getting back to you on this, but it appears that OTC data is already available. There is no special behavior to retrieve data, simply use the OTC symbol:

```python
from iexfinance.stocks import Stock

hktty = Stock("HKTTY")
hktty.get_chart()
```

or

```python
from iexfinance.stocks import get_historical_data

get_historical_data("HKTTY", start="20180101", end="20190101")
```
