### ISSUE TITLE
"There was a client-side error with your request." Only when using Test token

### ISSUE THREAD

**Issue by diogomota** [addisonlynch/iexfinance#130]
My code works fine when the token env var is set to the production version but when I replace that with the test token (the one starting with Tsk_...) an error is thrown saying 

"There was a client-side error with your request."

IEX_API_VERSION is set to iexcloud-beta
requests I'm trying to make: get_financials() + get_historical_data()   (Both fail  when using the test token)

Is this a known issue or is there additional setup work to get the api working with test tokens?

**Comment by addisonlynch** [comment]
Set ``IEX_API_VERSION`` to ``iexcloud-sandbox``. I will update the documentation to better reflect this.

**Comment by sl00k** [comment]
Hi,
can you pls post an example code here? I just cant get this cloud thing to work :(

**Comment by addisonlynch** [comment]
Closed #130 via 7cf902e
