### ISSUE TITLE
Production Key Works, But Sandbox Key doesn't

### ISSUE THREAD

**Issue by chprabhu** [addisonlynch/iexfinance#132]
## Summary (include Python version)
from iexfinance.stocks import Stock
import os
os.environ["IEX_API_VERSION"] = "iexcloud-beta"

aapl = Stock('AAPL', output_format='pandas', token={token})

When using my production key, I get back output. When using my sandbox key, I get back a "IEXAuthenticationError: The query could not be completed. There was a client-side error with your request." error

### Date/time of issue
May 1, 2019 - 4:02pm

### Expected behavior
Get back a pandas dataframe with the balance sheet for Apple

### Actual behavior
Error message stated above

**Comment by addisonlynch** [comment]
To use the sandbox environment, set ``IEX_API_VERSION`` to ``iexcloud-sandbox``. I will update the documentation to better reflect this. Sorry for the confusion!

**Comment by chprabhu** [comment]
Thanks, just tried that, and now get the following error:
IEXVersionError: The requested endpoint is only available using IEX Cloud

**Comment by addisonlynch** [comment]
What version are you using? Need to have the latest dev version for this to work.

**Comment by chprabhu** [comment]
I'm using 0.4.0, I just installed it using `pip install iexfinance`

Is this the latest version?

**Comment by addisonlynch** [comment]
The ``master`` branch of this repo is the development version of ``iexfinance``...try:

```python3
pip3 install git+https://github.com/addisonlynch/iexfinance
```

**Comment by jordangrodecki** [comment]
> To use the sandbox environment, set `IEX_API_VERSION` to `iexcloud-sandbox`. I will update the documentation to better reflect this. Sorry for the confusion!

Thank you for this. Was about to go digging a lot further to get sandbox support as I couldn't see it obviously.

**Comment by tylerheald** [comment]
Same issue. Updated to latest version per your comment but receive:

NameError                                 Traceback (most recent call last)
<ipython-input-17-7c45581ee664> in <module>
      2 import iexfinance
      3 from iexfinance.stocks import get_historical_data
----> 4 IEX_API_VERSION = iexcloud-sandbox
      5 
      6 start = datetime(2018, 1, 1)

NameError: name 'iexcloud' is not defined

**Comment by Ferdihei** [comment]
i had troubles to understand how to set the sandbox token 
i mean it is not dificult, but maybe the following short code example in the documentation would help. 

Source: https://codereview.stackexchange.com/questions/227322/pulling-financial-data-via-iex-cloud-api

import os
# Set IEX Finance API Token (Test)
os.environ['IEX_API_VERSION'] = 'iexcloud-sandbox'
os.environ['IEX_TOKEN'] = 'your-sandbox-token'

Place in doc: https://addisonlynch.github.io/iexfinance/stable/sandbox.html

**Comment by GardnerCode** [comment]
> i had troubles to understand how to set the sandbox token
> i mean it is not dificult, but maybe the following short code example in the documentation would help.
> 
> Source: https://codereview.stackexchange.com/questions/227322/pulling-financial-data-via-iex-cloud-api
> 
> ```python
> import os
> # Set IEX Finance API Token (Test)
> os.environ['IEX_API_VERSION'] = 'iexcloud-sandbox'
> os.environ['IEX_TOKEN'] = 'your-sandbox-token'
> ```
> 
> Place in doc: https://addisonlynch.github.io/iexfinance/stable/sandbox.html

Thank you I was lost trying to properly set up the sandbox, this code worked for me.
