### ISSUE TITLE
Pull only specific fields within endpoint?

### ISSUE THREAD

**Issue by kevinpcollins** [addisonlynch/iexfinance#139]
## Summary (include Python version)
Is it possible to perform an API call to only certain fields within an endpoint? Specifically, I'm asking about the get_balance_sheet or get_financials endpoints. For example, if it would possible to perform get_shareholderEquity(). I see from the docs ([here](https://addisonlynch.github.io/iexfinance/stable/stocks.html#additional-methods)) that a couple field methods are available under get_key_stats, but wondering if there a hack-y way to expand it to other endpoints. 

Context - I'm setting up a small app under the IEX launch data plan, but hitting my usage limits fast. Trying to find ways to reduce the volume from some of the expensive calls (e.g., get_balance_sheet, get_key_stats). 

### Date/time of issue
5/17/19

### Expected behavior
N/A

### Actual behavior
N/A

**Comment by kevinpcollins** [comment]
Played around with this a bit more and looks like this may be possible, but not likely to affect data weights. For example, the two calls below had the same effect on my total useage (3000 messages)
- https://cloud.iexapis.com/stable/stock/gs/balance-sheet?filter=shareholderEquity&token=XXX
- https://cloud.iexapis.com/stable/stock/gs/balance-sheet?token=XXX

Maybe I'm missing a simple solution, but it seems like the IEX API basically prevents a workaround.

**Comment by addisonlynch** [comment]
Could this be achieved with the [Data Points](https://iexcloud.io/docs/api/#data-points) endpoint? I believe that allows retrieval of individual fields. I will take a look.

**Comment by addisonlynch** [comment]
``iexfinance`` actually supports this using the ``filter_`` keyword argument to ``Stock`` method calls, such as:

```python
from iexfinance.stocks import Stock
aapl = Stock("AAPL")
aapl.get_balance_sheet(filter_="shareholderEquity")

# 39242091
```

though IEX does not support reduced message weighting for filtered calls on most endpoints. I may open an issue for this in their [repo](https://github.com/iexg/iex-api).

**Comment by kevinpcollins** [comment]
Thanks Addison! Let me know if you do end up opening an issue in their repo - I would make a ton of use out of the filter argument if it did reduce message weighting. For now, I'm working around it with some procedures to cache the data I'm pulling.
