### ISSUE TITLE
End of Python 2 Support

### ISSUE THREAD

**Issue by addisonlynch** [addisonlynch/iexfinance#144]
~``iexfinance`` will end support for Python 2 on or after July 1, 2019.~

``iexfinance`` will end support for Python 2 in version 0.5.0 (Q3 2019)

*Note: test suite support for Python 2 ended in* ``iexfinance`` 0.4.1

**Comment by MasterOdin** [comment]
When is the expected release of 0.5.0? Right now (or at least as of 6 days ago), any new installation of iexfinance is going to be broken as pandas 0.25.0 was released which removed Python 2 support and as part of it removed `pandas.compat.string_types` which is used here:
https://github.com/addisonlynch/iexfinance/blob/a8400737878c5727db5e588eb0f5f0e7f6c0dffc/iexfinance/utils/__init__.py#L6

An immediate fix would be to replace that import with something like:
```python
import sys
string_types = str if sys.version_info[0] >= 3 else basestring
```

but would be unnecessary if 0.5.0 was released.

**Comment by addisonlynch** [comment]
@MasterOdin this has been repaired in release 0.4.3, in which python 2 compatibility remains. Python 2 compatibility will end in the 0.5.0 release.

**Comment by MasterOdin** [comment]
Good to hear and thank you for your efforts!
