### ISSUE TITLE
IEXAuthenticationError  after downloading  some historical prices

### ISSUE THREAD

**Issue by fightthepower** [addisonlynch/iexfinance#146]
python 3.x

I am new to iexfinance and I am trying to download historical prices from it. I used this way to download the prices
```
api_key="PUBLISHABLE KEY"
df=get_historical_data('F', start_date=datetime(2018,1,1),end=datetime(2019,1,1),output_format='pandas',token=api_key)
df.to_csv('F.csv')
```
It initially worked and downloded about 30ish files then it stopped working and giving me this error 

```
 raise auth_error("The query could not be completed. "
iexfinance.utils.exceptions.IEXAuthenticationError: The query could not be completed. There was a client-side error with your request.
```

But this  works `https://cloud.iexapis.com/stable/stock/gs/balance-sheet?filter=shareholderEquity&token=api_key`

**Comment by k128** [comment]
Check your messages used on the IEX cloud site.  This happened to me and it says I used all my messages.  I'm trying to figure out if there's a way to use the old IEX to get historical data to avoid this.

**Comment by sl00k** [comment]
were you able to fix it? i used the platform a few weeks ago.
now i cant get it to work.
even the example:
from iexfinance.stocks import Stock

a = Stock("AAPL", token="<YOUR AUTH TOKEN>")
a.get_quote()

gives me that error

**Comment by k128** [comment]
No, I have the same issue and haven't found a solution yet.  If you find one, let me know.

**Comment by addisonlynch** [comment]
What version of ``iexfinance`` are you using? Please provide all ``IEX_`` environment variables

**Comment by k128** [comment]
I'm using iexfinance 0.4.1.  I was not using any IEX_ environment variables.  I believe after reviewing the IEX documentation that this is intended behavior, since they count each row of historical data as 10 messages and I probably did end up having 50k rows between runs I did.  I'm just surprised that it used to be unlimited free historical data on the old version but on the new version I'm limited to kilobytes per month.

**Comment by addisonlynch** [comment]
Releasing an optimized version of ``get_historical_data`` in 0.4.2 (live now in dev version / master git branch). That should help for single day calls (2 message), which can be chained for multiple days if needed.
