### ISSUE TITLE
IEX Historical queries still cost too much...(5000 IEX messages instead of 10)

### ISSUE THREAD

**Issue by shlomikushchi** [addisonlynch/iexfinance#156]
## Summary (include Python version)
you have missed an important thing in my solution:
https://github.com/addisonlynch/iexfinance/pull/148

the issue wasn't just one day.. it could b a week a month.. 6 months...
there's no need to pay for the whole year.
the solution was - iterating the required days and getting day by day.
so if I want a week - I iterate every day, then build the result DF ot json and return the whole week
costing 2*5 = 10 points for a week...
your solution is still 5000 points...
please look at the code.. or talk to me.

**Comment by addisonlynch** [comment]
I think the issue of extending the optimization beyond a single day is that in some cases (such as the one you've presented above) you will need to chain >100 API calls. This is not ideal behavior for a wrapper, and can be handled on the client side.

**Comment by addisonlynch** [comment]
I would recommend opening an issue with the provider (https://github.com/iexg/iex-api) requesting date ranges for historical data.

**Comment by shlomikushchi** [comment]
ok, I will do that.
thanks
