### ISSUE TITLE
Select symbols break get_dividends

### ISSUE THREAD

**Issue by kevinpcollins** [addisonlynch/iexfinance#160]
## Summary (include Python version)
Python 3.7. Hitting a ValueError of 'year 0 is out of range' when running get_dividends() with the stock "ICL". Running through a large loop and no other stocks hit the error before ICL, so it may be the only one. 

`x = Stock("ICL", output_format = 'pandas')`
`y = x.get_dividends(range = '5y')`

### Date/time of issue
July 16th, 2019.

**Comment by addisonlynch** [comment]
Seems to be working now. Can you confirm? Thanks!
