### ISSUE TITLE
Authentication issue (worked well previously)

### ISSUE THREAD

**Issue by Jiaxi68** [addisonlynch/iexfinance#162]
## Summary (include Python version)

The API is not working well for requesting one-minute market data. 
I store the key in my script. However, there is an error with authentication.
Please let me know your thought. Thank you.
I use Python 3.7. 

### Date/time of issue
July 19, 2019.

### Expected behaviour
one-minute intraday data. Worked well previously.
get_historical_intraday(company_stock_code, dt, token=iex_finance_API_key)
### Actual behaviour

~/anaconda3/lib/python3.7/site-packages/iexfinance/base.py in _handle_error(self, response)
    176                 raise auth_error(auth_msg)
    177             else:
--> 178                 raise IEXQueryError("The query could not be completed. "
    179                                     "There was a client-side error with your "
    180                                     "request.")

**Comment by addisonlynch** [comment]
Are you using a free tier (start) account? It seems as if the provider has disabled access to some endpoints for this account type.

**Comment by Jiaxi68** [comment]
Thank you so much for your reply. I really appreciate it. Yes, I am using the free version. If that is the reason, I will try to purchase and keep you posted.

**Comment by addisonlynch** [comment]
I contacted the provider to try to determine if any endpoints have changed, as I am not seeing any entries in their changelog for this week.

See https://github.com/iexg/IEX-API/issues/1135

**Comment by Jiaxi68** [comment]
Thank you so much!

**Comment by w601sxs** [comment]
Will this work in the free version of the new API? 

I get an IEXAuthenticationError when I do the following -

    batch = Stock(portfolio, token = "<my_secret_token_from_iex_cloud>") 
     
    current_prices = batch.get_price() 
    historical_prices = batch.get_chart(range = '1d') 

Same issue when I use the publishable token. What am I doing wrong?

**Comment by addisonlynch** [comment]
Closing. See discussion in #161
