### ISSUE TITLE
Dividend Ranges

### ISSUE THREAD

**Issue by TechniumUnlimited** [addisonlynch/iexfinance#169]
Hi, if I do for instance, this:

`for obj in stock_tickers:
    print(stocks[obj].get_dividends(range='1y'))`

I only get seemingly one dividend and have no way to decipher what a full year of dividends pays out for any given stock, as such:

`>>> [{'exDate': '2018-10-30', 'paymentDate': '2018-11-19', 'recordDate': '2018-10-31', 'declaredDate': '2018-10-18', 'amount': 0.77, 'flag': 'Increase', 'currency': 'USD', 'description': 'Texas Instruments Hikes Quarterly Dividend 24.2%', 'frequency': 'Quarterly', 'date': '2019-09-05'}]`

How does the dividend range parameter work?

**Comment by addisonlynch** [comment]
See https://iexcloud.io/docs/api/#dividends for dividends documentation.
