### ISSUE TITLE
Print error content (Enhancement)

### ISSUE THREAD

**Issue by Voyz** [addisonlynch/iexfinance#171]
## Summary (include Python version)
Python 3.6.7
iexfinance 0.4.2

When error is returned from the server, currently iexfinance prints a generic message defined in `iexfinance.base._handle_error`. However, the `response` object contains the `text` field that can be used to provide more information on the error that occurred.

The `IEXQueryError` object overrides the `__str__` to always print the same message: `return "An error occurred while making the query."`. When this confusing override is removed, the `response.text` can be added to the handling of errors, for instance: 

```
raise IEXQueryError(response.text,
                                     "The query could not be completed. "
                                    "There was a client-side error with your "
                                    "request.")
```
And similarly to the other error handling cases.

A number of not-so-uncommon errors are hidden away from the user without providing such mechanism. For instance, when running out of messages quota or using a published key instead of a secret one - we currently receive the same generic error and are required to deeply analyse the causes (essentially modifying the iexfinance code ourselves), instead of having a clear message printed when the error occurs.

### Date/time of issue
10 Sep 2019 (and earlier)

### Expected behavior
Print the content of the error

### Actual behavior
Generic "An error occurred while making the query." is displayed

**Comment by addisonlynch** [comment]
Thanks. The error output could be more detailed.

**Comment by Voyz** [comment]
Thanks! :)
