### ISSUE TITLE
OpenSSL.SSL.Error

### ISSUE THREAD

**Issue by shinhwas** [addisonlynch/iexfinance#173]
## Summary (include Python version)
I am using Anaconda 2019.07 with python3.7 on windows 10 with intelliJ.
When I try to fetch data, I got error like below.
`
OpenSSL.SSL.Error: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')]
`

If you can adding verify=False option on request, it would be great.
`
response = self.session.get(url=url, params=params, verify=False)
`
https://github.com/addisonlynch/iexfinance/blob/6edfde16f70e6a0ae9691dc2279ed5327c02971e/iexfinance/base.py#L159

### Date/time of issue
2019-09-11

### Expected behavior
Fetch the data

### Actual behavior
Occurred Error.

**Comment by addisonlynch** [comment]
It seems like your client was not able to verify the server's certificate. I would make sure that your SSL CA is up to date, which should resolve the issue.
