### ISSUE TITLE
Filter based on industry

### ISSUE THREAD

**Issue by CapitalZe** [addisonlynch/iexfinance#175]
Not so much an issue as a query.

I'm looking for a way to filter out IEX data based on industry.

For example, I'd like to call and display in a pandas df a single industry of symbols at a time.

EG: Finance, Tech, Pharma, etc.

I am thinking if there is a variant of this:

```
from iexfinance.refdata import get_symbols
get_symbols(output_format='pandas', token=XXX)
```

I've looked here [https://iexcloud.io/docs/api/#sectors](https://iexcloud.io/docs/api/#sectors) but can not make much sense of it.

Any pointers would be appreciated.

**Comment by addisonlynch** [comment]
Hi, sorry for the delay on this.

You can use ``get_collections`` to obtain this:

```python3
from iexfinance.stocks import get_collections

get_collections("Technology", "sector")
```

Where the first argument is the collection name and the second is the collection type.

**Comment by addisonlynch** [comment]
Hi, sorry for the delay on this.

You can use ``get_collections`` to obtain this:

```python3
from iexfinance.stocks import get_collections

get_collections("Technology", "sector")
```

Where the first argument is the collection name and the second is the collection type.
