### ISSUE TITLE
CI: Ensure correct Python version support

### ISSUE THREAD

**Issue by addisonlynch** [addisonlynch/iexfinance#18]
Currently in setup.py:

>      'Programming Language :: Python',
>      'Programming Language :: Python :: 2',
>      'Programming Language :: Python :: 2.6',
>      'Programming Language :: Python :: 2.7',
>      'Programming Language :: Python :: 3',
>      'Programming Language :: Python :: 3.3',
>      'Programming Language :: Python :: 3.4',
>      'Programming Language :: Python :: 3.5',

Travis only runs tests for Python 3.5, per travis.yml

**TODO***
* Update TravisCI to test all listed compatible Python versions
     * If problems arise with tests, patch compatibility issues if able, else remove version from compat list

**Comment by hugovk** [comment]
Python 2.6 and 3.3 are both EOL and no longer receive security updates (or any other kind) from the core Python team. They're also little used.

Here's the pip installs for iexfinance from PyPI for last month (via `pypinfo --start-date -58 --end-date -28 --percent --pip --markdown iexfinance pyversion`):

| python_version | percent | download_count |
| -------------- | ------: | -------------: |
| 2.7            |   40.0% |              6 |
| 3.6            |   33.3% |              5 |
| 3.5            |   20.0% |              3 |
| 3.4            |    6.7% |              1 |


And here's monthly pip installs from all of PyPI (13 December 2017, via `pypinfo --percent --pip --markdown "" pyversion`).

| python_version | percent | download_count |
| -------------- | ------: | -------------: |
| 2.7            |   77.7% |    435,636,261 |
| 3.6            |    8.8% |     49,199,570 |
| 3.5            |    8.4% |     46,927,461 |
| 3.4            |    3.9% |     21,843,444 |
| 2.6            |    1.1% |      6,194,026 |
| 3.3            |    0.1% |        554,661 |
| 3.7            |    0.1% |        428,159 |
| 3.2            |    0.0% |         38,570 |
| None           |    0.0% |         21,921 |
| 2.8            |    0.0% |             35 |
| 3.1            |    0.0% |             26 |

It's generally a good idea to test on those versions you support, like 2.7, and 3.4-3.6.
