### ISSUE TITLE
An error occurred while making the query.

### ISSUE THREAD

**Issue by sayaliwalke30** [addisonlynch/iexfinance#183]
## Summary (include Python version)
Python 3

### Date/time of issue

11-07-2019
### Expected behavior
For every function I get same error.
get_price(), get_balance_sheet() and so on...

**Comment by addisonlynch** [comment]
What tier is your IEX cloud account?

**Comment by noobmaster29** [comment]
I'm not getting the same issue but I am getting the follow error when I try to use get_price():
IEXQueryError: An error occurred while making the query.

I have already pip updated to the latest version. All the other queries seems to work fine.

I can run get_price() when I set the IEX_API_VERISON to iexcloud-sandbox.

**Comment by jrlarke** [comment]
Per the IEX Cloud documentation, get_price() is only available for paid accounts:

**Notes**
Only included with paid subscription plans

**Comment by sayaliwalke30** [comment]
okay..Thank you
