### ISSUE TITLE
Blocked by corporate firewall

### ISSUE THREAD

**Issue by k-ji** [addisonlynch/iexfinance#184]
SSLError: HTTPSConnectionPool(host='cloud.iexapis.com', port=443): Max retries exceeded with url: /v1/stock/market/batch?symbols=AAPL&types=quote&token=sk_bd6e77f5dac94993a29c8c00bec89bc7 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))

is there any way to get around it?

**Comment by addisonlynch** [comment]
Perhaps use a proxy? This is not an iex issue.
