### ISSUE TITLE
Specific Date Argument + get_income_statement

### ISSUE THREAD

**Issue by MineSafety** [addisonlynch/iexfinance#187]
## Summary (include Python version)
I am trying to pull quarterly financial data (e.g., net income from the income statement, book value from the balance sheet, etc), but would like to pass a specific date as an argument. 

(Mac OS 10.15 / Python 3.7)

### Actual Behavior
For example, `income = company.get_income_statement(period="quarter", last='4')` returns the  last 4 quarters of income statements. 

### Expected behavior
But is there a way to pass a specific date as an argument, so that I can see the last 4 quarter of income statements from _that date;_ rather than from the most recent filing? Something like.. `income = company.get_income_statement("20170401", period="quarter", last='4')`

**Comment by Millerlm012** [comment]
I don't know how to help you... But I posted something four days ago about how the response I was getting was a weird number thing. Anyway I was just wondering if you had any idea why I was getting the response I was getting.

**Comment by addisonlynch** [comment]
At this time date / date range functionality is not supported natively by iexcloud. PRs for a custom implementation are welcome.
