### ISSUE TITLE
ImportError: No module named 'iexfinance'

### ISSUE THREAD

**Issue by daneaker** [addisonlynch/iexfinance#198]
installed the package using 

pip3 install iexfinance

Tells me all requirements are already satisfied

when I run my script, it gives me this error:

ImportError: No module named 'iexfinance'

Any help is greatly appreciated

**Comment by samuelchodur** [comment]
Ensure your script is using the same Python environment that you installed iexfinance to. If your distribution defaults to Python 2, this may be the cause of the problem.
