### ISSUE TITLE
Is there a balance sheet function?

### ISSUE THREAD

**Issue by bh32** [addisonlynch/iexfinance#200]
I'm wondering if the function to pull balance sheet info from IEX Cloud has been developed in iexfinance and if not will that be done at some point?

**Comment by ashnabaziz** [comment]
IEXAuthenticationError: The query could not be completed. Invalid auth token.

Does that mean I need a paid IEX Cloud Account for Financial Fundamentals Data?

Thanks

**Comment by bh32** [comment]
Probably - I know that at least the balance sheets require a paid account.

By the way, did you pull this through iexfinance? If so, could you share the command you used? (I can't find it in the time series etc.)

**Comment by addisonlynch** [comment]
Yes. ``get_balance_sheet()`` method of ``Stock``:

https://addisonlynch.github.io/iexfinance/stable/stocks.html#balance-sheet

```python
from iexfinance.stocks import Stock

aapl = Stock("AAPL")
aapl.get_balance_sheet()
```

Note that this will not work with free tier accoutns
