### ISSUE TITLE
get_historical_data throws exception: ValueError: DataFrame index must be unique for orient='index'.

### ISSUE THREAD

**Issue by MLLeKander** [addisonlynch/iexfinance#202]
## Summary (include Python version)

Python version: 3.7.3

Reproduction steps:
```
import os

os.environ['IEX_TOKEN'] = ...
os.environ['IEX_OUTPUT_FORMAT'] = 'json'
os.environ['IEX_API_VERSION'] = 'iexcloud-sandbox'

from iexfinance.stocks import get_historical_data

get_historical_data(['AAPL','ZM'], '20190101', '20200403', close_only=True)
```

This produces the following traceback:
```
Traceback (most recent call last):
  File "repro.py", line 11, in <module>
    get_historical_data(['AAPL','ZM'], '20190101', '20200403', close_only=True)
  File "/home/michael/.local/share/virtualenvs/Stocks-z8jCOmud/lib/python3.7/site-packages/iexfinance/stocks/__init__.py", line 44, in get_historical_data
    close_only=close_only, **kwargs).fetch()
  File "/home/michael/.local/share/virtualenvs/Stocks-z8jCOmud/lib/python3.7/site-packages/iexfinance/base.py", line 210, in fetch
    return self._output_format(data, fmt_j=fmt_j, fmt_p=fmt_p)
  File "/home/michael/.local/share/virtualenvs/Stocks-z8jCOmud/lib/python3.7/site-packages/iexfinance/stocks/historical.py", line 84, in _output_format
    result[sym] = result[sym].to_dict('index')
  File "/home/michael/.local/share/virtualenvs/Stocks-z8jCOmud/lib/python3.7/site-packages/pandas/core/frame.py", line 1433, in to_dict
    raise ValueError("DataFrame index must be unique for orient='index'.")
ValueError: DataFrame index must be unique for orient='index'.
```

If I switch the `output_format` to `pandas`, I also get an exception. I have not tested this in any API version other than `iexcloud-sandbox`.

Interestingly, this very similar query returns the expected response:
```
get_historical_data(['AAPL','ZM'], '20190101', '20200402', close_only=True)
```

This query also works, but only if `IEX_OUTPUT_FORMAT` is `pandas`:
```
get_historical_data(['AAPL','GOOGL'], '20190102', '20200403', close_only=True)
```

### Date/time of issue

April 14, 2020, 17:36 EDT.

### Expected behavior

Combined dataframe with NaNs where data is missing.

### Actual behavior

ValueError exception.

**Comment by dolanwill** [comment]
Has there been any update on this? I get this error for certain symbols when querying "close" to the current date.

e.g. the following queries throw this error (today is 6/16):
get_historical_data('NRZ', datetime(2016-01-01), datetime(2020-06-15))
get_historical_data('NRZ', datetime(2016-01-01), datetime(2020-06-12))

but this one is fine:
get_historical_data('NRZ', datetime(2016-01-01), datetime(2020-06-11))

cursory stackoverflow for the pandas error shows this:
https://stackoverflow.com/questions/29271520/valueerror-dataframe-index-must-be-unique-for-orient-columns

thanks!

**Comment by Olshansk** [comment]
I cannot repro this error right now, but I have run into it in the past. My current workaround is to wrap the result of `get_historical_data` with the function below:
```
def drop_duplicate_indecies(df):
    return df.loc[~df.index.duplicated(keep='first')]

df = drop_duplicate_indecies(get_historical_data('NRZ', datetime(2016-01-01), datetime(2020-06-11)))
```

**Comment by singlecheeze** [comment]
The root of the issue is that iex is publishing duplicate data points per date, for example for ticker "A". So your workaround of dropping duplicate indexes seems the only way to keep pandas happy as it insures uniqueness like IEX should.

https://cloud.iexapis.com/stable/stock/a/chart/2y?token=<insert your production token here without brackets>

`[
  {
    "date": "2020-09-25",
    "uClose": 97.69,
    "uOpen": 95.96,
    "uHigh": 98.14,
    "uLow": 95.77,
    "uVolume": 1028618,
    "close": 97.69,
    "open": 95.96,
    "high": 98.14,
    "low": 95.77,
    "volume": 1028618,
    "currency": "",
    "change": 1.35,
    "changePercent": 1.4013,
    "label": "Sep 25, 20",
    "changeOverTime": 0.370895
  },
  {
    "date": "2020-09-25",
    "uClose": 97.69,
    "uOpen": 95.96,
    "uHigh": 98.14,
    "uLow": 95.77,
    "uVolume": 1028618,
    "close": 97.69,
    "open": 95.96,
    "high": 98.14,
    "low": 95.77,
    "volume": 1028618,
    "currency": "",
    "change": 0,
    "changePercent": 0,
    "label": "Sep 25, 20",
    "changeOverTime": 0.370895
  }
]`

**Comment by singlecheeze** [comment]
Edit: @Olshansk I just tried your workaround and it didn't work-around anything....

**Comment by Olshansk** [comment]
Sorry about that :(

**Comment by singlecheeze** [comment]
@Olshansk no worries! What I should have asked is how you got it to work? Did you have create a new class and overwrite the method?

**Comment by Olshansk** [comment]
```
data = [
  {
    "date": "2020-09-25",
    "uClose": 97.69,
    "uOpen": 95.96,
    "uHigh": 98.14,
    "uLow": 95.77,
    "uVolume": 1028618,
    "close": 97.69,
    "open": 95.96,
    "high": 98.14,
    "low": 95.77,
    "volume": 1028618,
    "currency": "",
    "change": 1.35,
    "changePercent": 1.4013,
    "label": "Sep 25, 20",
    "changeOverTime": 0.370895
  },
  {
    "date": "2020-09-25",
    "uClose": 97.69,
    "uOpen": 95.96,
    "uHigh": 98.14,
    "uLow": 95.77,
    "uVolume": 1028618,
    "close": 97.69,
    "open": 95.96,
    "high": 98.14,
    "low": 95.77,
    "volume": 1028618,
    "currency": "",
    "change": 0,
    "changePercent": 0,
    "label": "Sep 25, 20",
    "changeOverTime": 0.370895
  }
]

df = pd.DataFrame(data)  

def drop_duplicate_indecies(df):
    return df.loc[~df.index.duplicated(keep='first')]
df_formatted = drop_duplicate_indecies(df.set_index(['date']))
df_formatted
```

Here is a colab link with a reference: https://colab.research.google.com/drive/1pXhzjnZ6nNP03Vms27oNueNkzTHrGTo5?usp=sharing
