### ISSUE TITLE
does iexfinance support connecting through proxy?

### ISSUE THREAD

**Issue by qtalen** [addisonlynch/iexfinance#204]
## Summary (include Python version)
python 3.7

### Date/time of issue
today

I want to use iexfinance with a https or socks5 proxy server， but I cant find any documents about this .
Does any knews how to do this?
Thanks a lot.

**Comment by addisonlynch** [comment]
This may work but I do know that iexcloud may block some proxies/vpns per #145. Not an ``iexfinance`` issue, however. Good luck!
