### ISSUE TITLE
Stock.get_short_ratio() return KeyError

### ISSUE THREAD

**Issue by ofirmg** [addisonlynch/iexfinance#206]
## Summary (include Python version)
version 0.4.3 (using iexfinance.__version__)

### Date/time of issue
4/24/2020

### Expected behavior
RUNNING:
from iexfinance.stocks import Stock
stock = ["AAPL"]
stock = Stock(stock)
stock.get_short_ratio()

Expected: Getting short ratio

### Actual behavior
KeyError: 'shortRatio'
It seems like the key_stats object does not have this entry.

**Comment by SaymV** [comment]
Yes it looks like the key-stats endpoint no longer has a "short ratio". The advanced-stats endpoint has **"putCallRatio"**, would that be the same thing? 

Aside: the advanced stats endpoint is a paid-plan only feature.

**Comment by ofirmg** [comment]
So there is no more free access to it? It is not a bug?

**Comment by addisonlynch** [comment]
This is no longer available. ``get_short_ratio`` will be deprecated in 0.5.0.
