### ISSUE TITLE
would you consider an IEXSymbolError suppression parameter?

### ISSUE THREAD

**Issue by riptusk331** [addisonlynch/iexfinance#207]
It seems like right now if you you create a `Stock` object with a list that includes an invalid symbol and run a method on that object like `get_price`, the method raises a symbol error and your request is basically tossed out.

I currently deal with this by catching the IEXSymbolError, popping the violating symbol from my list, and trying again. Would you be open to adding an optional parameter to either the base `Stock` class or the methods to ignore symbol errors and substitute the missing data with 0 or `N/A` or an empty string? Then it just moves on with the rest of the valid symbols.

If so I'd be happy to take a crack at implementing it.

**Comment by addisonlynch** [comment]
Yes. This is similar to #194 and #202. I'd like to rewrite this for 0.5.0 such that we do not throw errors for individual symbols. You are welcome to take a look at it. If not I should have it repaired by next week for a release mid-May

**Comment by addisonlynch** [comment]
Actually I will fix it. Thanks!

**Comment by riptusk331** [comment]
sounds good...if you need help or someone to test let me know!

**Comment by riptusk331** [comment]
Any update on this? I needed this to work, so I fixed it fairly simply for my use case. Described below. Happy to commit and test further if you want.


Add an instance variable to ```Stock``` to indicate you want to mute symbol errors:

```self.mute_symbol_error = kwargs.get("mute_symbol_error", False)```

Modify the ```_get_endpoint``` method in ```Stock``` slightly. If it encounters a missing symbol, it checks the mute_symbol_error variable and will add ```Unknown symbol``` to the results instead of raising an exception.

```
for symbol in self.symbols:
    if symbol not in data:
        if not self.mute_symbol_error:
            raise IEXSymbolError(symbol)
        result[symbol] = 'Unknown symbol'
    else:
        if endpoint not in data[symbol]:
            result[symbol] = []
        else:
            result[symbol] = data[symbol][endpoint]
```

Lastly, update the ```_handle_error``` method of the ```_IEXBase``` class to not raise an exception if the response is for an unknown symbol (it returns 404 status and says 'Unknown symbol'). I 

```
if status_code == 404 and response.text == "Unknown symbol":
    return {"Error": response.text}
```

So you should be able to use this by just doing

```
> stock = Stock('NOTASTOCK', mute_symbol_error=True)
> stock.get_quote()

> stock = Stock(['NOTASTOCK', 'AAPL'], mute_symbol_error=True)
> stock.get_quote()
```
yields
```
> Unknown symbol
> {'NOTASTOCK': 'Unknown symbol',
>  'AAPL': { ... } }
```

Quick and dirty but it works.

**Comment by addisonlynch** [comment]
An empty ``DataFrame`` is now returned when a certain symbol is invalid. Sorry for the delay on this.
