### ISSUE TITLE
Incorrect usage of Historical price messages with get_historical_data function

### ISSUE THREAD

**Issue by amatar1956** [addisonlynch/iexfinance#210]
## Summary (include Python version)
Python 3.7.3 
iexfinance 0.4.3
I used the function get_historical_data as follows:

 get_historical_data("FB", start=start, end=end,
                    output_format='pandas', close_only=False, token = token) 

with start=2020-05-11 and end=2020-05-15
An incorrect, incredibile amount of Historical Price messages were used 
### Date/time of issue
2020-05-18 17:00

### Expected behavior
The function got the correct data:
![Annotazione 2020-05-18 183640](https://user-images.githubusercontent.com/50156933/82237923-b4462100-9936-11ea-94e8-7407c45399ec.jpg)

but when I checked the message use in the iexcloud console I found that 2.530 Historical Price messages were used by the function instead of the 50 expected messages. 

I tried to use directly the iex cloud API 

https://cloud.iexapis.com/stable/stock/FB/chart/5d?token=<token>

I got the same data, but the correct numer of Historical Price messages were used 

### Actual behavior
The function get_historical_data consumes an incorrect number of Historical Prices messages

**Comment by tomermes** [comment]
happened to me too, drained many of my messages budget :(

**Comment by dolanwill** [comment]
I have the same behavior, the HistoricalReader downloads the entire 5 year dataset, then just slices it for the dates you made the get_historical_data() call with. 

That is terrible! It uses thousands more message credits than it should.

iexfinance/stocks/historical.py self.chart_range() -
sets the query's timeframe to be 5y, 2y or 1y rounded up based on the starting year you query with

iexfinance/stocks/historical.py:77 -
 where it slices the dataframe to the queried dates.

in your docs (https://addisonlynch.github.io/iexfinance/stable/stocks.html) it reads:
Certain endpoints such as Historical Data, which are unrelated to specific symbols, are supported by top-level functions (i.e. iexfinance.stocks.get_historical_data). This function is optimized to achieve the lowest possible message count for retrieval in a single request.

either I am missing something or it does the exact opposite of optimizing!

**Comment by dolanwill** [comment]
if anyone is following along, I found that if you do not specify an end date parameter in your call to get_historical_data(), it will only query IEX with the date you specified, not rounded-up-to-1y/3y/5y.

**Comment by yjlou** [comment]
@dolanwill  You are the life saver!  After removing the end time, the daily historical price only costs 2 messages (per day). Awesome!
