### ISSUE TITLE
How to use <stocks.get_earnings()> correctly?

### ISSUE THREAD

**Issue by ARTMRZN** [addisonlynch/iexfinance#212]
Hi Gents
### Expected behavior
i've used stocks.get_earnings() method to get last 4 quarters earnings of TSLA. Code is bellow.

tsla = Stock('TSLA')
earnings = tsla.get_earnings(period=4)

### Actual behavior
however i got only last quarter earnings report w EPSReportDate as 2020-04-29

Do you have some examples of correct usage of this method (or alternatives with get_earnings_today())? Can you show me how to get an annual earnings reports?

Best

**Comment by vahtos** [comment]
It seems that the "period" parameter is working, but "last" is not:

```
tsla = Stock('TSLA')
earnings = tsla.get_earnings(last=5, period='annual')
print(earnings)
```

> [{'actualEPS': 0.03, 'consensusEPS': 0, 'announceTime': 'ACM', 'numberOfEstimates': 24, 'EPSSurpriseDollar': 0.03, 'EPSReportDate': '2020-01-24', 'fiscalPeriod': 'FY ending in 2019', 'fiscalEndDate': '2019-12-18', 'yearAgo': -1.38, 'yearAgoChangePercent': 1.0451, 'currency': None}]
