### ISSUE TITLE
get_estimates() missing parameters

### ISSUE THREAD

**Issue by vahtos** [addisonlynch/iexfinance#213]
## Summary (include Python version)
The method Stock.get_estimates() is missing the last and period parameters (per the [IEX Cloud API documentation](https://iexcloud.io/docs/api/#estimates))

### Expected behavior
```
tsla = Stock('TSLA', output_format="pandas")
estimates = tsla.get_estimates(period="quarter", last=4)
```

Should produce the estimates for the next 4 quarters.

### Actual behavior

> TypeError: get_estimates() got an unexpected keyword argument 'period'

The get_estimates() method does not accept parameters.

**Comment by addisonlynch** [comment]
Adding in the new parameters for estimates, though it appears that only 1 period is available and ``last`` does not work.

Query:

``https://sandbox.iexapis.com/stable/stock/twtr/estimates?last=4&period=annual&token=``

Response:

```json
{
    "symbol": "TWTR",
    "estimates": [
        {
            "consensusEPS": 0.28,
            "announceTime": "BTO",
            "numberOfEstimates": 32,
            "reportDate": "2021-02-01",
            "fiscalPeriod": "Q4 2020",
            "fiscalEndDate": "2020-12-28",
            "currency": "USD"
        }
    ]
}

```

Issue opened with IEX https://github.com/iexg/IEX-API/issues/1606
