### ISSUE TITLE
Iexfinance not working with Dash.

### ISSUE THREAD

**Issue by mcket747econ** [addisonlynch/iexfinance#215]
## Summary (include Python version)
I am trying to use the iexfinance api with get_historical_data to load data into a data frame and then from there into a plotly visualization hosted on Dash. Instead I keep getting errors. 

Code: 
import dash
import dash_core_components as dcc
import dash_html_components as html
import iexfinance
from iexfinance.stocks import get_historical_data
import datetime
from dateutil.relativedelta import relativedelta ###I'm not sure what this package does for us.
import plotly.graph_objs as go

start = datetime.datetime.today() - relativedelta(years=5)  #I guess relative delta changes time relative to some time we choose
end = datetime.datetime.today()

df = get_historical_data("GE",start=start,end=end,output_format='pandas',token="pk_529ed4bdd5d44db88ebc79c182c1a508")
print(df.head())
trace_close = go.Scatter(x=list(df.index),
                         y=list(df.close),
                         name="Close",
                         line=dict(color="#f44242"))

data = [trace_close]
layout = dict(title='Stock Chart',
              showlegend=False)

fig = dict(data=data,layout=layout)
app = dash.Dash()
app.layout = html.Div([
    html.Div(html.H1(children='Hello World')),
    html.Label("DASH GRAPH"),
    html.Div(
        dcc.Graph(id='Stock Chart',
                  figure=fig)
    )
])

if __name__=='__main__':
    app.run_server(debug=True)

### Date/time of issue
6/10/2020 1:00PM

### Expected behavior
Visualization produced in web browser

### Actual behavior
Traceback (most recent call last):
  File "C:/Users/mcket747-es/documents/dashapp/myapp.py", line 13, in <module>
    df = get_historical_data("GE",start=start,end=end,output_format='pandas',token="pk_529ed4bdd5d44db88ebc79c182c1a508")
  File "C:\Users\mcket747-es\Documents\dashapp\venv\lib\site-packages\iexfinance\stocks\__init__.py", line 44, in get_historical_data
    close_only=close_only, **kwargs).fetch()
  File "C:\Users\mcket747-es\Documents\dashapp\venv\lib\site-packages\iexfinance\base.py", line 209, in fetch
    data = self._execute_iex_query(url)
  File "C:\Users\mcket747-es\Documents\dashapp\venv\lib\site-packages\iexfinance\base.py", line 165, in _execute_iex_query
    return self._handle_error(response)
  File "C:\Users\mcket747-es\Documents\dashapp\venv\lib\site-packages\iexfinance\base.py", line 178, in _handle_error
    raise IEXQueryError("The query could not be completed. "
iexfinance.utils.exceptions.IEXQueryError: An error occurred while making the query.

**Comment by addisonlynch** [comment]
This does not appear to be an ``iexfinance`` issue. Please re-open if the problem persists. Thanks!
