### ISSUE TITLE
IEXQueryError: An error occurred while making the query (404): Not Found

### ISSUE THREAD

**Issue by cgates30** [addisonlynch/iexfinance#218]
## Summary (include Python version): 3.7.7

Free account. None of the common usage examples work (https://addisonlynch.github.io/iexfinance/stable/usage.html#). I always get the following error:

IEXQueryError: An error occurred while making the query (404): Not Found

`>>> from datetime import datetime
>>> from iexfinance.stocks import get_historical_data
>>> start = datetime(2020, 7, 1)
>>> end = datetime(2020, 7, 10)
>>> key = ******using my public key here
>>> df = get_historical_data('tsla',start,end,token=key)
`

**Comment by eazar001** [comment]
Confirmed on v0.5.0, on python v3.7.3

**Comment by eazar001** [comment]
@cgates30 this was several months ago, but maybe this will help:
```
    _URLS = {
        "v1": "https://cloud.iexapis.com/v1/",
        "stable": "https://cloud.iexapis.com/stable/",
        "latest": "https://cloud.iexapis.com/latest/",
        "beta": "https://cloud.iexapis.com/beta/",
        "sandbox": "https://sandbox.iexapis.com/v1/",
        "iexcloud-beta": "https://cloud.iexapis.com/beta/",
        "iexcloud-v1": "https://cloud.iexapis.com/v1/",
        "iexcloud-sandbox": "https://sandbox.iexapis.com/v1/",
    }
```

According to the source code  here you can choose from these different API branches. I set my `IEX_API_VERSION` environment variable to point to `stable`, and it worked for my use-case (getting peer groups). Hope that helps.

**Comment by lfender6445** [comment]
```
    _VALID_API_VERSIONS = (
        "v1",
        "stable",
        "latest",
        "beta",
        "sandbox",
        "iexcloud-beta",
        "iexcloud-v1",
        "iexcloud-sandbox",
    )
```

to clarify for future visitors, youll want to set IEX_API_VERSION to one of those
