### ISSUE TITLE
Historical data more than 5 years still Erroring

### ISSUE THREAD

**Issue by genthug** [addisonlynch/iexfinance#220]
## Summary (include Python version)
Running Py 3.7.3, Anaconda  2019.07, iexfinance 0.4.3

Attempted to run the get_historical_data function on something >5 years old. Does not allow, says that only data <5 years is allowed to be downloaded. Went and found issue #94 as IEX's API docs said that 15 years was allowable, but I understand gathering 15 years of data probably pretty hefty in a package. After finding that, went back to it and attempted to grab <5 years worth of data via specifying a start date of 2010,1,1 and end date of 2014,12,31. This still failed; went and looked into iexfinance/stocks/historical.py and found that although the comment at the top states calculating from start and end, if you specify an end it does not use it. It uses a datetime.now() item to calc how long of a set of data to pull.

### Date/time of issue
09/11/2020 ~730pm

### Expected behavior
Based on issue #94 expected to allow 15 years of data at the same time, unless there was a commit I missed somewhere that reverted this (which is entirely possible and if so I apologize). At the very least, a check in historical.chart_range that allows for selection of <5 years of dates outside of the current date - 5 years via specification of end - start < 5y which seems to be where the root issue is.

### Actual behavior
Historical data not available to be pulled past current date - 5 years.

**Comment by NexVeridian** [comment]
I'm guessing you're on the free tier?

"Access to Historical Prices from more than 5 years ago is only included with paid subscriptions"

Source is [this link](https://iexcloud.io/docs/api/#historical-prices), in the notes section
or [ this link ](https://iexcloud.io/core-data-catalog/) if you hover over the 15 year box

**Comment by genthug** [comment]
I actually am not. If you look at the source code that I referenced in the above report you can see it has nothing to do with it hitting IEX at all and everything to do with the fact that there's an internal check in the package for a 5 year limiter.

For reference, I _can_ grab >5 years of data for a company if I just use requests to manually hit it instead of using iexfinance.

**Comment by NexVeridian** [comment]
Oh, are you using [the stable version or the dev version ](https://github.com/addisonlynch/iexfinance#install)

I think the dev version fixed #94 
in pull #168 on Aug 28, 2019
but the fix wasn't added to the pip version?

[historical.py on the version from Aug 28, 2019](https://github.com/addisonlynch/iexfinance/blob/6edfde16f70e6a0ae9691dc2279ed5327c02971e/iexfinance/stocks/historical.py)

[historical.py on the the current dev version](https://github.com/addisonlynch/iexfinance/blob/master/iexfinance/stocks/historical.py)

on the pip version![Capture](https://user-images.githubusercontent.com/46305192/98309275-e861dc80-1f7e-11eb-891e-8d8544ca4662.PNG)

**Comment by genthug** [comment]
Ahh, that makes sense. I probably should've thought to check dev and stable. Thanks!
