### ISSUE TITLE
Cannot import get_historical_data

### ISSUE THREAD

**Issue by harshita130602** [addisonlynch/iexfinance#229]
## Summary (include Python version)
Using iexfinance and I want to import get_historical data. I am using the following syntax to import it:

`from iexfinance.stocks import get_historical_data`

It is still showing me the following error:

File "file.py", line 1, in <module>
    from iexfinance.stocks import get_historical_data
ImportError: No module named iexfinance.stocks

I am not able to figure it out. Did I miss something?

**Comment by NexVeridian** [comment]
use the dev version, the pip version is stable but out of date

pip install update git+git://github.com/addisonlynch/iexfinance 

or 

https://github.com/addisonlynch/iexfinance#install

**Comment by addisonlynch** [comment]
Are you still having problems with this? If so, what version if ``iexfinance`` are you using?

**Comment by harshita130602** [comment]
@addisonlynch  It is fine now. Thank you :)
