### ISSUE TITLE
ImportError: cannot import name 'Stock'

### ISSUE THREAD

**Issue by athenawisdoms** [addisonlynch/iexfinance#24]
Installed the package using

    pip install iexfinance

When I try to import the package, in Python 3.6

    from iexfinance import Stock

I get the error

	ImportError: cannot import name 'Stock'

Did I miss out something?

**Comment by aceidon** [comment]
I think the author changed it to "Share" instead of "Stock"

**Comment by addisonlynch** [comment]
Pip version is different than the current development version (which in this case is on the master branch of Github). Will be pushing a new release to Pypi (and pip) later this week which should resolve these issues. For now, I would recommend downloading the development version (see docs) until the latest features are released.

**Comment by addisonlynch** [comment]
RLS 0.3.0 (2/17/18) repairs these issues. Please re-open if further concerns arise.

**Comment by MKolaksazov** [comment]
from iexfinance.stocks import Stock
