### ISSUE TITLE
List of sectors

### ISSUE THREAD

**Issue by burrittresearch** [addisonlynch/iexfinance#241]
## Summary (include Python version)
Python 3.8.6, iexfinance==0.5.0

Hello: I looked through the documentation and could not find an equivalent for producing a list of sectors.  Here is the api call from IEX Cloud:

Call: https://sandbox.iexapis.com/stable/ref-data/sectors?token=

[IEX Cloud documentation: https://iexcloud.io/docs/api/#sectors](https://iexcloud.io/docs/api/#sectors)

[iexfinance documentation: https://addisonlynch.github.io/iexfinance/stable/market-info.html#collections](https://addisonlynch.github.io/iexfinance/stable/market-info.html#collections)

And if these kinds of requests are not recommended here, please let me know! I will post to SO.

### Date/time of issue
Current

### Expected behavior
Looking for list of sectors

### Actual behavior
Don't know if it's available

**Comment by addisonlynch** [comment]
Use ``refdata.getsectors`` https://addisonlynch.github.io/iexfinance/stable/refdata.html#sectors

**Comment by burrittresearch** [comment]
Thanks, Addison. And if you ever need any help with this project, please let me know!
