### ISSUE TITLE
Please change the default requests for the batch symbol

### ISSUE THREAD

**Issue by evancarter-iex** [addisonlynch/iexfinance#27]
Hi there,

Can you please change the batch request to not request 10 different api endpoints by default and instead make the user specify which requests they are making?  

We are seeing lots of users leave the defaults and add thousands of symbols which isnt ideal from our end. In addition, many of the endpoints being requested return duplicate data that is returned in other ones in the same request. Thanks.

**Comment by addisonlynch** [comment]
Will change for upcoming release (3 days our or so). Sorry about that

**Comment by addisonlynch** [comment]
Repaired in e3348db17cd0aa0061e057d610b4b85e4b42e91d

Endpoints are now downloaded as requested, rather than at instantiation. Will be released with 0.3.0 (2/16/18).
