### ISSUE TITLE
Should include Current Liabilities

### ISSUE THREAD

**Issue by Fabelsady** [addisonlynch/iexfinance#40]
There is a function to pull out current debt but not current liabilities. Current liabilities is a more useful feature for finance people to calculate current ratio. 

Please consider adding it in.

Thanks,
Fabelsady

**Comment by addisonlynch** [comment]
Which function are you referring to for current debt? The [financials](https://iextrading.com/developer/docs/#financials) group of the Stocks endpoints allows extraction of the following:

* Current Debt
* Total Debt
* Total Liabilities

doesn't seem as if current liabilities are supported from the provider.
