### ISSUE TITLE
Add default date parameters

### ISSUE THREAD

**Issue by addisonlynch** [addisonlynch/iexfinance#41]
In similar style to Pandas Datareader's ``_sanitize_dates``, we should probably have the date period for functions such as ``get_historical_data`` and ``get_stats_daily`` default to somthing like 1/1/2015 for ``start`` and today for ``end``. This would allow null ``start`` and ``end`` parameters to make valid requests for those methods...docs will also need to indicate the same. 

Still thinking about this.

**Comment by stubs** [comment]
I can take care of this for you.

**Comment by addisonlynch** [comment]
@stubs that would be great. Submit a PR and will review. Thank you!

**Comment by addisonlynch** [comment]
@stubs may need to rebase if you're working on this now (just merged a couple other pulls)
