### ISSUE TITLE
Expected close test fails

### ISSUE THREAD

**Issue by akbennett** [addisonlynch/iexfinance#45]
self = <tests.test_stock.TestHistorical object at 0x7fda905e40f0>

    def test_single_historical_json(self):
    
        f = get_historical_data("AAPL", self.good_start, self.good_end)
        assert isinstance(f, dict)
        assert len(f["AAPL"]) == 73
    
        expected1 = f["AAPL"]["2017-02-09"]
>       assert expected1["close"] == 132.42
E       assert 130.3577 == 132.42

I was making sure I had everything installed properly, but ran into this test failure.  As I started to chase down the fail, I get another fail as the historical high seems to be different.  I was ok with the close, as it could be adjusted close, but when high was different, I started to question what it 'should' be. 

-- My environment:
https://github.com/akbennett/iex-docker

**Comment by addisonlynch** [comment]
@akbennett thanks. Seems as if their data is changing a bit over time.
