### ISSUE TITLE
Is there any method to get list(gainers, losers, etc)?

### ISSUE THREAD

**Issue by Junatum** [addisonlynch/iexfinance#52]
Hi,
First of all, thank you for hard work.
I have a quick question.
Is there any method to get list(gainers, losers, etc)? I couldn't find it.
( IEX document link is https://iextrading.com/developer/docs/#list )
Please let me know.

**Comment by addisonlynch** [comment]
I never actually added the List endpoint, as its formatting was different from the others. Seems trivial to implement now, though. I'll try to get it in before 3.2 (Monday). If not it'll hold off till the next release. Thanks for the comment!

**Comment by addisonlynch** [comment]
@Junatum done. Will be released by the end of the day.

**Comment by Junatum** [comment]
@addisonlynch Thanks a lot!
