### ISSUE TITLE
Package requirements - Pandas ==0.21.0

### ISSUE THREAD

**Issue by bjaikaran** [addisonlynch/iexfinance#69]
## Summary (include Python version)
Python 3.6 - Is there a huge need for Pandas version 0.21.0? Could you write the requirements to be pandas>=0.21.0 vice pandas==0.21.0?

### Date/time of issue
2018-07-12

**Comment by addisonlynch** [comment]
This is actually repaired as of the current master branch. I would recommend downloading the dev version (``pip install git+https://github.com/addisonlynch/iexfinance``) for now, until the next release.
