### ISSUE TITLE
Stock() top-level function restricts batches to lot size 99 rather than 100

### ISSUE THREAD

**Issue by ddewitt9** [addisonlynch/iexfinance#71]
Very minor and quick fix, but in `__init__.py`, `Stock()` throws a ValueError when a lot size of 100 is used, even though the API is capable of handling it. I've made this change myself on a forked version and can confirm that it works.

Line 40:
`elif isinstance(symbols, list) and 0 < len(symbols) < 100:`
should be:
`elif isinstance(symbols, list) and 0 < len(symbols) <= 100:`

**Comment by addisonlynch** [comment]
Thanks! A pull would be appreciated!
