### ISSUE TITLE
get_dividends not implemented ?

### ISSUE THREAD

**Issue by chrisfs** [addisonlynch/iexfinance#80]
## Summary (include Python version)
Is get_dividends not implemented yet ? Python 3

### Date/time of issue
09/19/2018 12:57 pm

### Expected behavior
Docs says get_dividends is a top level function that can be used

### Actual behavior
When I add "from iexfinance import get_dividends as div" to a script , I get an error:
ImportError: cannot import name 'get_dividends'

**Comment by addisonlynch** [comment]
``get_dividends`` is a method of the ``Stock`` class. You'll need to create a ``Stock`` instance to call it:

```python
from iexfinance import Stock

aapl = Stock("AAPL")
aapl.get_dividends()
```

**Comment by chrisfs** [comment]
Thank you, 
The docs list it in the Reference section. Perhaps it's a doc bug instead.

**Comment by addisonlynch** [comment]
@chrisfs thanks! I'll look into it.
