### ISSUE TITLE
get_historical_data - key error 'date'

### ISSUE THREAD

**Issue by dsl-dsl** [addisonlynch/iexfinance#82]
## Summary (include Python version)
Python 3.6.4

### Date/time of issue
25th September 2018

### Expected behavior
to get empty dictionary or empty dataframe

### Actual behavior
When calling get_historical_data for symbol 'ZNWAA' I get an keyerror 'date'. This happens on setting index od 'Date'. As long as IEX do not provide any data for this symbol the index can not be set on empty dataframe.

**Comment by addisonlynch** [comment]
This should throw a ``TDQueryError``.
