### ISSUE TITLE
lookback

### ISSUE THREAD

**Issue by drsramd** [addisonlynch/iexfinance#84]
## Summary (include Python version)
python 3.6.4
stock.StockReader.get_time_series returns '1m' lookback date regardless of lookback parameter passed (e. g. pass '6m' still returns '1m' data

### Date/time of issue
2018/11/03

### Expected behavior
data from 2018/06/03 to 2018/11/03 returned

### Actual behavior
data from 2018/10/03 to 2018/11/03 returned

**Comment by addisonlynch** [comment]
Use the ``range_`` parameter to specify the desired period.

For ``1m``:

```python
from iexfinance import Stock

aapl = Stock("AAPL")
aapl.get_time_series(range_='1m')
```

for ``6m``:

```python
a.get_time_series(range_='6m')
```

This should resolve your issue.
