### ISSUE TITLE
intraday historical data

### ISSUE THREAD

**Issue by Fux002** [addisonlynch/iexfinance#89]
Does anyone know if its possible to request historical intraday data?

1 minute data for example?

**Comment by fernandodelacalle** [comment]
Yes you can with the request: https://api.iextrading.com/1.0/stock/aapl/chart/date/20181120
but i think is not implemented in the iexfinance lib.

**Comment by addisonlynch** [comment]
This will be implemented in 0.3.5, releasing this week.

**Comment by Fux002** [comment]
Ok thx a lot!

**Comment by fernandodelacalle** [comment]
you can extract the iex minute bar since 12-12-2016 form the tops files:
https://iextrading.com/trading/market-data/#hist-download
