### ISSUE TITLE
Documenting Return Keys

### ISSUE THREAD

**Issue by jackmoody11** [addisonlynch/iexfinance#90]
I was looking through the latest documentation and noticed that a lot of endpoints say something like `Returns: Stocks Key Stats endpoint data` and doesn't give detail on the return values (without having to go to the iextrading website to look them up through the link).

Is this something that would be beneficial to have on the iexfinance documentation? If so, I would be glad to help do this.

**Comment by addisonlynch** [comment]
Any PRs helping with the documentation would be greatly appreciated! They could do a much better job of explaining things.

**Comment by addisonlynch** [comment]
@jackmoody11 I forgot about this issue. I sent you in the wrong direction on documenting the return keys, and I apologize! I'm refactoring ``iexfinance`` now on the ``refactor-docs`` branch, but anything you see that isn't clear in the documentation after this done, feel free to fix...thanks!
