### ISSUE TITLE
inconvenient format of minute data for pandas

### ISSUE THREAD

**Issue by MoritzImendoerffer** [addisonlynch/iexfinance#95]
## Summary
Python 3.6 on latest anaconda
The function `get_historical_intraday('AAPL', date, format='pandas')` returns strings with format "10:01 AM" which can be conveniently converted to a datetime object and consecutively to an index for a dataframe. However for eg. 10:00 it puts out "10 AM" which causes an error when doing something like `[pd.to_datetime(i).strftime('%H:%M:%S') for i in df.label.values]`. This is only a very minor issue but in my opinion the output format should be consistent for all timestamps.

### Date/time of issue
27.Dez.18

**Comment by addisonlynch** [comment]
I think you are right...that's not so convenient. A PR to fix this would be welcomed...I won't be able to get around to it until after the new year.

Thanks!

**Comment by addisonlynch** [comment]
There is a bug in the repaired implementation:

https://github.com/addisonlynch/iexfinance/blob/7a77848ca0a792dbfbed6c17e70e25d3b9e20620/iexfinance/stocks/historical.py#L111-L116

``to_datetime`` is given the time only, and therefore defaults to the current date. This has now been repaired and will be merged with version 4.0.
