### ISSUE TITLE
get_historical_data exception on ['open' 'high' 'low'] not in index

### ISSUE THREAD

**Issue by jud2012** [addisonlynch/iexfinance#96]
I'm running the following command- get_historical_data(['AAPL', 'RODI'], '2018-12-20', '2018-12-30')
RODI symbol return the following exception "['open' 'high' 'low'] not in index"

### Expected behavior
 _output_format in historical.py should catch exception and print them to stdout

### Actual behavior
got exception and i'm unable to retrieve data on other symbols in array

**Comment by addisonlynch** [comment]
What version of ``iexfinance`` are you using?

```python
from iexfinance.stocks import get_historical_data

get_historical_data(['AAPL', 'RODI'], '2018-12-20', '2018-12-30')
```

seems to be working for me in 0.3.5.

**Comment by jud2012** [comment]
I’m using the same version 0.3.5

Thanks

**Comment by jud2012** [comment]
Uninstall and install package fixed this issue
