### ISSUE TITLE
fail to get data for symbols with "-"

### ISSUE THREAD

**Issue by jud2012** [addisonlynch/iexfinance#98]
## Summary (include Python version)
I'm using iexfinanace 0.3.5, I'm trying to get data for symbols with "-" 
for example ECF-PA, FHN-PA and more, those symbols return "Symbol not found", although they exist on yahoo web page (https://finance.yahoo.com/quote/FHN-PA/history?p=FHN-PA)

My Code:
from iexfinance import Stock, get_historical_data
sym = Stock('ECF-PA')
sym.get_price()

### Expected behavior
getting price correctly.
data exist on https://finance.yahoo.com/quote/FHN-PA/history?p=FHN-PA

### Actual behavior
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/xambala/anaconda2/lib/python2.7/site-packages/iexfinance/stocks/base.py", line 427, in get_price
    return self._get_endpoint("price", fmt_p=fmt_p, params=kwargs)
  File "/opt/xambala/anaconda2/lib/python2.7/site-packages/iexfinance/stocks/base.py", line 83, in _get_endpoint
    raise IEXSymbolError(symbol)
iexfinance.utils.exceptions.IEXSymbolError: Symbol ECF-PA not found.

**Comment by addisonlynch** [comment]
These symbols are not available from the provider. See below link:

https://api.iextrading.com/1.0/stock/ECF-PA/price

Let me know if there is a separate issue. Thanks!
