### ISSUE TITLE
Return dict when stock symbol array is one symbol

### ISSUE THREAD

**Issue by rsgmon** [addisonlynch/iexfinance#99]
## Summary (include Python version)
Python version 3.6
When requesting a real time quote with an array, return the same type and format (in this case a dictionary) regardless of the length of the array.

### Date/time of issue
01/09/19

### Expected behavior
batch = Stock(["TSLA", "AAPL"])
batch.get_price()
{'TSLA': 338.42, 'AAPL': 153.34}
batch = Stock(["TSLA"])
batch.get_price()
**{'TSLA': 338.42}**

### Actual behavior
batch = Stock(["TSLA", "AAPL"])
batch.get_price()
{'TSLA': 338.42, 'AAPL': 153.34}
batch = Stock(["TSLA"])
batch.get_price()
**338.42**

And thank you for the library!

**Comment by jackmoody11** [comment]
This would require a change to the following bit from base.py:

```python
def _get_endpoint(self, endpoint, params={}, fmt_p=None,
                      fmt_j=None, filter_=None):
    result = {}
    if filter_:
        params.update({"filter": filter_})
    self.optional_params = params
    self.endpoints = [endpoint]
    data = self.fetch(fmt_j=fmt_j, fmt_p=no_pandas)
    for symbol in self.symbols:
        if symbol not in data:
           raise IEXSymbolError(symbol)
        if endpoint not in data[symbol]:
           result[symbol] = []
        else:
            result[symbol] = data[symbol][endpoint]
    return self._output_format_one(result, fmt_p=fmt_p, fmt_j=fmt_j)
```

All that is needed is to change `return self._output_format_one(result, fmt_p=fmt_p, fmt_j=fmt_j)` to `return self._output_format(result, fmt_p=fmt_p, fmt_j=fmt_j)`

However, it looks like this behavior was intended, as many other functions rely on `_get_endpoint()` to return a single value if there is only one symbol. A workaround could be to use
```
>>>symbol="AAPL"
>>> batch = Stock([symbol])
>>> batch.get_price()
166.52
>>> if isinstance(batch.get_price(),float):
...     print({batch.symbols[0]: batch.get_price()})
...
{'AAPL': 166.52}
```
This is a relatively easy function to write while keeping the current behavior of iexfinance, as changing `_output_format_one()` would change many other pieces of code.

**Comment by rsgmon** [comment]
Thanks for reviewing and responding!
